../analyzebatch.pl \
../test1/ \
config=name,nsta,ngroup,nrawslotnum,tcpsegmentsize,ipcameradatarate,datamode,apalwaysschedulesfornextslot,contentionperrawslot \
stats=edcaqueuelength,tcpconnected,totalnumberofdrops,numberofmactxmissedack,numberoftransmissions,NumberOfDroppedPackets,AveragePacketSentReceiveTime,DropTCPTxBufferExceeded,IPCameraSendingRate,IPCameraReceivingRate

