../analyzebatch.pl \
/proj/wall2-ilabt-iminds-be/ns3ah/ipcamera_rto/ \
config=name,nsta,ngroup,nrawslotnum,tcpsegmentsize,ipcameradatarate,datamode,minrto,contentionperrawslot \
stats=edcaqueuelength,tcpconnected,totalnumberofdrops,numberofmactxmissedack,numberoftransmissions,NumberOfDroppedPackets,AveragePacketSentReceiveTime,DropTCPTxBufferExceeded,NumberOfTCPRetransmissions,NumberOfTCPRetransmissionsFromAP,TotalDozeTime,TCPCongestionWindow,IPCameraSendingRate,IPCameraReceivingRate

