../analyzebatch.pl \
../test1/ \
config=name,sensormeasurementsize,nsta,ngroup,nrawslotnum,trafficinterval,apalwaysschedulesfornextslot,contentionperrawslot \
stats=edcaqueuelength,tcpconnected,totalnumberofdrops,numberofmactxmissedack,numberoftransmissions,NumberOfDroppedPackets,AveragePacketSentReceiveTime,DropTCPTxBufferExceeded,totaldozetime,numberoftcpretransmissions,numberoftcpretransmissionsfromap,NumberOfAPScheduledPacketForNodeInNextSlot,jitter,reliability,interPacketDelayAtServer,interPacketDelayAtClient,interPacketDelayDeviationPercentageAtServer,interPacketDelayDeviationPercentageAtClient \
$@

#config=name,sensormeasurementsize,nsta,ngroup,nrawslotnum,trafficinterval,apalwaysschedulesfornextslot,contentionperrawslot \
#stats=edcaqueuelength,tcpconnected,totalnumberofdrops,numberofmactxmissedack,numberoftransmissions,NumberOfDroppedPackets,AveragePacketSentReceiveTime,DropTCPTxBufferExceeded,totaldozetime,numberoftcpretransmissions,numberoftcpretransmissionsfromap,NumberOfAPScheduledPacketForNodeInNextSlot,jitter,reliability,interPacketDelayAtServer,interPacketDelayAtClient,interPacketDelayDeviationPercentageAtServer,interPacketDelayDeviationPercentageAtClient
#

#config=rawconfigfile,trafficpath,payloadsize,nsta \
#stats=edcaqueuelength,goodput,totalnumberofdrops,numberofmactxmissedack,numberoftransmissions,NumberOfDroppedPackets,AveragePacketSentReceiveTime,DropTCPTxBufferExceeded,latency,reliability,totalpacketloss,jitter,reliability,interPacketDelayAtServer,interPacketDelayAtClient,interPacketDelayDeviationPercentageAtServer,interPacketDelayDeviationPercentageAtClient 
